### ISSUE TITLE
Compatible with C++17?

### ISSUE THREAD

**Issue by rpatters1** [Dugy/EzGz#3]
I didn't see anywhere in the readme as to what is the minimum version of c++ for this library. I'm trying to stick to c++17 for reasons. Is this library compatibile with this?

I would suggest adding the minimum c++ version to the readme.

Great project.

**Comment by Dugy** [comment]
The library requires C++20 because it uses concepts and `std::span`. You'd have to make some edits to get it running on C++17, but it shouldn't be too hard as they aren't used very heavily.

This is mentioned in the readme, which says it _depends only on the C++20 standard library._

**Comment by rpatters1** [comment]
Whoops, sorry I didn't see it.

If I can get it to work with C++17 (presumably testing `__cplusplus`), are you interested in a PR with the changes?

**Comment by Dugy** [comment]
I chose to use C++20 because it made the code more convenient. A bunch of `#ifdef` around every use of `std::span` would make the code even harder to work with than simply downgrading it to C++17.

But if you left the fork alive, I could add a link to it so that people without access to C++20 could use it.

**Comment by rpatters1** [comment]
Another option would be to create a C++17 branch. I could then issue a PR against that rather than the master branch. At any rate, I have it working. Very few changes were required other than to roll a C++17 version of `std::span` and to nop out the `concept` declarations with a macro. It would be pretty easy to separate the changes out into a `ezgz_env.hpp` header.

But I'm cool with keeping it in a fork if you don't want it in a separate branch.

**Comment by Dugy** [comment]
That looks like a way to make the code work on C++17 without scattering`#ifdef` across the main algorithms. All right, then, I will merge it if it won't be much of a burden for future development.

**Comment by rpatters1** [comment]
I'll post a PR of the changes as-is. If you are interested in them as-is, then that's fine. If you are interested but would rather split out a `ezgz_env.hpp` header that is then included back, I'll be happy to do that as well.

**Comment by Dugy** [comment]
Okay, post it as it is and I will see for myself.
