### ISSUE TITLE
Versioning and Tests

### ISSUE THREAD

**Issue by rpatters1** [Dugy/EzGz#7]
Since you mentioned you are working on a significant new feature branch, I thought I would bring up some nice-to-haves. You have no doubt thought of many or all of them already, so this issue is more to get an idea of what your plans are.

## Versioning

I hope you will label a version before merging a major new feature branch. It makes it easier for outside projects to reference the project with a submodule. Some projects use tags, others use branches, and some use both. I have found version branches to be particularly helpful because it is easy to find them, especially in a git GUI frontend.

At some point it may become necessary to drop support for C++17. Or it may be that you would like to refactor for C++23 eventually and drop C++20. All of this can be easily controlled and documented with version branches.

## Tests

I did not run the tests yesterday on C++17, because there is no build script for them. I'm guessing you may have one privately. It might be nice to have a test script in the repo that builds and runs the test on any supported C++.

It might also be nice to set up a GitHub Action that builds and runs the tests on every PR to `master`. This is something I might be able to contribute if you are interested.

**Comment by Dugy** [comment]
Regarding versioning, I have seen that being done but I have never been doing that. The current master could be called version 0.1 or something.

Regarding tests, the source files have a shebang that makes them executable, but I this CMake script should work too:
```
cmake_minimum_required(VERSION 3.5)

project(EzGz LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(ezgz_test ezgz_test.cpp)
add_executable(ezgz_decompress ezgz_decompress.cpp)

target_compile_options(ezgz_test PRIVATE "-g")
target_compile_options(ezgz_test PRIVATE -Wall -Wextra -Wpedantic)

target_compile_options(ezgz_decompress PRIVATE "-g")
target_compile_options(ezgz_decompress PRIVATE -Wall -Wextra -Wpedantic)

set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
target_link_libraries(ezgz_test PRIVATE Threads::Threads)
target_link_libraries(ezgz_decompress PRIVATE Threads::Threads)
```

I have no idea how to set up GitHub Actions. If you know how to do it, I would gladly accept your help.

**Comment by rpatters1** [comment]
How would you feel about moving the tests into a subfolder? I think it might be cleaner and underscore the fact that the only thing one needs is the header.

**Comment by rpatters1** [comment]
I'm hitting a snag, which is that `ezgz_test.cpp` contains a bug on line 199 when it calls `reader.getBits(29)`. That value (29) causes an index-out-of-bounds assert on line 412 of `ezgz.hpp`:

```
result &= upperRemovals[amount];
```

It's weird that neither Clang nor GCC care about this, but MSVC sure does. I added an explicit assert bounds check (as a test) in ezgz, and that fails on Clang (and presumably GCC as well).

Meanwhile, MSVC is reporting lots of lint that the other compilers don't, so I am going to work on a delint PR.

**Comment by rpatters1** [comment]
Okay, I have the GitHub workflow ready to go. It builds and runs `ezgz_test` on unbuntu, macos, and windows for both C++17 and C++20 (a total of 6 jobs). The bug I discovered only manifests in the Debug build on Windows, so by using Release config it will allow the workflow to complete without errors.

Before I can create a PR I need decisions on

- Whether and/or how much of #8 you want to include.
- Whether to put the tests (along with the CMakeLists.txt file) in a subdirectory.

**Comment by Dugy** [comment]
It's possible that the out of bounds read is an actual bug. I haven't seen any warnings even when using valgrind, so I a not sure why it suddenly starts happening.

By the way, MSVC does bound checking for all containers in debug mode while Clang and GCC don't. This is a double edged blade since it also makes it slower and triggers false positives in case the value is used only to obtain a behind-the-end pointer.

I think I will add the CMakeLists when I merge my feature branch, which I might be able to do tomorrow. I need to change it there.

**Comment by rpatters1** [comment]
I'm almost certain the out of bounds read is an actual bug. You can make it happen every time by adding a bounds check assert right before line 412. The number passed in is 29, but the size of the array is something like 11.

FWIW I've made significant changes to the CMakeLists file, to accommodate different compilers with different options and the like for the GitHub action. I was going to include it with that PR. One of the main reasons I would like to put the tests in a subfolder is to but the CMakeLists file there. Having only `exgz.hpp` in the root folder underscores and reassures that it is truly a single header only.

**Comment by Dugy** [comment]
All right, commit the CMakeFiles, I will include my changes into it.

**Comment by rpatters1** [comment]
I added CMakeLists and .gitignore to #8.
